load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_license//rules:license.bzl", "license")

package(
    default_applicable_licenses = [":license"],
    default_visibility = ["//visibility:public"],
)

license(
    name = "license",
    license_kinds = [
        "@rules_license//licenses/spdx:BSD-2-Clause",
    ],
    license_text = "LICENSE",
    visibility = [":__subpackages__"],
)

cc_library(
    name = "lz4",
    srcs = [
        "lib/lz4.c",
        "lib/lz4file.c",
        "lib/lz4frame.c",
        "lib/lz4hc.c",
        "lib/xxhash.c",
    ],
    hdrs = [
        "lib/lz4.c",
        "lib/lz4.h",
        "lib/lz4file.h",
        "lib/lz4frame.h",
        "lib/lz4frame_static.h",
        "lib/lz4hc.h",
        "lib/xxhash.h",
    ],
    copts = ["-fno-delete-null-pointer-checks"],
    includes = ["lib"],
    licenses = ["LICENSE"],
    visibility = ["//visibility:public"],
)
